### ISSUE TITLE
Maximum storage for complete book

### ISSUE THREAD

**Issue by caraya** [FriendsOfEpub/eBookPerfChecklist#11]
Provide guidance on what the maximum size for an ebook is depending on the reader

**Comment by JayPanoz** [comment]
For reference: 

- iBooks: 2GB (can’t find this in iBooks spec though)
- Google Play Books: 2GB ([help](https://support.google.com/books/partner/answer/3424254?hl=en&ref_topic=3238502#guidelines))
- Kobo: 1GB ([spec](https://github.com/kobolabs/epub-spec#limitations-and-maximums))
- Kindle: 650MB ([Guidelines](https://kindlegen.s3.amazonaws.com/AmazonKindlePublishingGuidelines.pdf))
- B&N Nook: unclear if 600MB or 20MB ([stackexchange](http://ebooks.stackexchange.com/questions/626/is-the-file-size-limit-for-nook-epub-files-still-600mb))

**Perf:**

- on devices which have been used for a while (e.g. iPad Mini), huge size may degrade perf in a visible manner;
- huge size files on eInk Readers also a no-go. 

**UX:**

- downloading;
- storing → old joke about Apple selling 16GB devices but a lot of Android devices in use can actually be 8GB. After a few years, 32GB likely isn’t enough too.

**Comment by caraya** [comment]
Thanks
